name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 #   - name: install node v12
  #    uses: actions/setup-node@v1
   #   with:
    #    node-version: 14
    - name: npm install
      run: npm install
    - name: tsc
      uses: iCrawl/action-tsc@v1
      with: 
        project: /src  
